### ISSUE TITLE
Simplify Deployment Process

### ISSUE THREAD

**Issue by tylersamples** [boisebrigade/courtbot#17]
ExCourtbot should be deployable with the least amount of work possible. Everything that can have a sane default should and everything that doesn't require someone to figure out should be set automatically if possible.

### Heroku
Should configure Postgres and schedule import and notifications. Upon clicking deploy, should only have to retrieve user credentials and follow the frontend configuration steps to get ExCourtbot working.
- [Deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button): `app.json`
  - https://devcenter.heroku.com/articles/app-json-schema

### Docker
Given a modest `docker-compose.yml` such as:
```yml
version: "3.3"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=excourtbot
    volumes:
      - postgres-data:/var/lib/postgresql/data

  excourtbot:
    image: codeforboise/excourtbot:latest
    environment:
      - PORT=4000
      - HOST=localhost
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/excourtbot
    ports:
      - "4001:4000"
    links:
      - postgres
```
ExCourtbot should be able to serve the frontend where the end user should only have to retrieve user credentials and follow the frontend configuration steps to get ExCourtbot working.

#### Additional Considerations
- Postgres SSL should be configurable.
- HTTPS should be documented and an example provided
